### ISSUE TITLE
Add floating point support

### ISSUE THREAD

**Issue by o2sh** [02sh/add-one#5]
Help our "add-one" crate to handle floating point numbers.

**Comment by pjlast** [comment]
I'll give it a shot :)

**Comment by o2sh** [comment]
Hi @GuineaPiet,
You should probably check the PR of @sn99 beforehand, to see if you can do better.

**Comment by pjlast** [comment]
https://github.com/o2sh/add-one/pull/7

I think my implementation works as intended :)
